### ISSUE TITLE
Config for pretraining the ResNet*-WS backbones

### ISSUE THREAD

**Issue by vadimkantorov** [shenyunhang/DRN-WSOD-pytorch#15]
Hi!

What config / command-line were used for pretraining the `ResNet*-WS` backbones (the provided pickled weights)?

Thanks!

**Comment by vadimkantorov** [comment]
Found it in imagenet.py file and shell scripts calling it

**Comment by shenyunhang** [comment]
> Found it in imagenet.py file and shell scripts calling it

This script is pytorch version. The released models are all trained on Caffe2.
