### ISSUE TITLE
Pretrained weights for R50-WS contains some strange tensors

### ISSUE THREAD

**Issue by vadimkantorov** [shenyunhang/DRN-WSOD-pytorch#16]
Hi!

What are the fully-connected  `'fc1_w', 'fc1_b', 'fc2_w', 'fc2_b', 'last_out_L1000_w', 'last_out_L1000_b'` layer weights contained in `resnet50_ws_model_120_d2.pkl`?

These look like fully-connected layers for VGG? For ResNet there should be no such layers, right?

The shapes are
``` 
>>> loaded['fc1_w'].shape
(2048, 100352) == 2048 * 7 * 7
>>> loaded['fc1_b'].shape
(2048,)
>>> loaded['fc2_w'].shape
(4096, 2048)
>>> loaded['fc2_b'].shape
(4096,)
>>> loaded['last_out_L1000_w'].shape
(1000, 4096)
>>> loaded['last_out_L1000_b'].shape
```

Thank you!

**Comment by shenyunhang** [comment]
> 
> These look like fully-connected layers for VGG? For ResNet there should be no such layers, right?
> 

Yes, those layers are pretrianed.
