### ISSUE TITLE
Supervised objectness score from MCG used for modulation of proposal features

### ISSUE THREAD

**Issue by vadimkantorov** [shenyunhang/DRN-WSOD-pytorch#21]
It seems that MCG objectness scores are used to modulate proposal features: https://github.com/shenyunhang/DRN-WSOD-pytorch/blob/DRN-WSOD/projects/WSL/wsl/modeling/roi_heads/roi_heads_wsddn.py#L286

From what I understand, MCG proposals objectness score is trained using strong supervision.

Do you have results without this modulation?

**Comment by vadimkantorov** [comment]
Without this modulation, I'm getting before test-time aug ~66% corloc on OICRREG WSR18 config and ~64% on OICRREG WSR50 config.

**Comment by shenyunhang** [comment]
This part mainly follows WSDDN and its official implemention in MATLAB.
In our experiments, MCG scores have similar gains (maybe smaller) as EdgeBox scores (table 1 in WSDDN), so we keep it for consistency framework.

**Comment by vadimkantorov** [comment]
wetectron does not have this multiplication (and I also didn't use it when working on ContextLocNet), so I think this is a bit confusing when not mentioned. I'm not sure, but I think OICR also didn't use it. But thanks for explaining!

Using EdgeBox score to compute objectness for given proposals is interesting because it's not learned.
