### ISSUE TITLE
Why is only the last box regression module learned?

### ISSUE THREAD

**Issue by vadimkantorov** [shenyunhang/DRN-WSOD-pytorch#23]
In all `reg` configs:
```
WSL:
  REFINE_NUM: 4
  REFINE_REG: [False, False, False, True]
```

Why is only the last box regression layer learned?

Intermediate ones don't help?

**Comment by bityangke** [comment]
if all refine branches use regression, we need recalculate roi feats

**Comment by vadimkantorov** [comment]
just FYI wetectron chose to not recalculate roi feats and still do regression: https://github.com/NVlabs/wetectron/blob/master/wetectron/modeling/roi_heads/weak_head/weak_head.py#L118

i guess introduces some randomness

**Comment by bityangke** [comment]
base on my experience, regression for only the last branch brings better results

**Comment by vadimkantorov** [comment]
How are the final box scores computed? Do I understand correctly that :

1. when refinement is enabled, simply the last refinement branch scores are taken? i.e. no averaging or merging the instance lists
2. when refinement is not enabled, the scores/boxes are merged across refinement branches

**Comment by vadimkantorov** [comment]
Also, in my experiments on VOC07 WSR18 performs considerably better than WSR50, quite strange

**Comment by shenyunhang** [comment]
Hi @vadimkantorov, thanks for your queries.
Sorry for the delayed response, as I do not Sign in to GitHub recently.



> In all `reg` configs:
> 
> ```
> WSL:
>   REFINE_NUM: 4
>   REFINE_REG: [False, False, False, True]
> ```
> 
> Why is only the last box regression layer learned?
> 
> Intermediate ones don't help?

Yes, It seem intermediate regressions do not help.
It may require careful selection of pseudo boxes.




> Also, in my experiments on VOC07 WSR18 performs considerably better than WSR50, quite strange

I think deeper network may overfit the data in sometimes.
