### ISSUE TITLE
Would you mind briefly introducingthis repo, instead of Detectron2?

### ISSUE THREAD

**Issue by sisrfeng** [shenyunhang/DRN-WSOD-pytorch#6]

**Comment by sisrfeng** [comment]
Oh I find that:  

https://github.com/shenyunhang/DRN-WSOD-pytorch  
On this site, the README is about detectron2

https://github.com/shenyunhang/DRN-WSOD-pytorch/tree/DRN-WSOD/projects/WSL
On this site, the README is about this paper

**Comment by shenyunhang** [comment]
Hi, this repo is the pytorch version of our codes (original Caffe2 code is [here](https://github.com/shenyunhang/DRN-WSOD)).
And our code is integrated as a project based on Detectron2.
By this way, we may be able to take advantage of some techniques from fully supervised tasks in the future.
