### ISSUE TITLE
Some questions about the network

### ISSUE THREAD

**Issue by Cynthiacoding** [shenyunhang/DRN-WSOD-pytorch#7]
Hello, I am a beginner in this field. I recently discovered some magical designs I didn’t understand when running the code. I hope to get your help.

1. In the WSDDN(2016) paper, the author Bilen said

> Region-level features are further processed by two fully connected layers

What is the difference between this design and the  Redundant Adaptation Neck design in this paper?

2.In the part of Robust Information Flow, you said 

> " we replace the original stem block with three conservative 3 × 3 convolutions, with the first and third convolutions followed by 2×2 MaxPool layers."

I want to confirm with you whether the first convolution here refers to the stem structure.  If so，I noticed that the maxpool stride following the third convolutions is 1. I want to know the role of this layer.

Look forward to your reply！

**Comment by shenyunhang** [comment]
Below is our reply:

1. They have the same structure.

2. The stem block refers to the first stage of backbones.
And the maxpool is still required to get informative activations.

**Comment by Cynthiacoding** [comment]
Thank you very much for your answer. This work is great and very helpful to me. 
Looking forward to your next work！
